# Generated by Django 4.2.2 on 2023-06-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0002_invoice_line_eight_invoice_line_eight_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='line_eight',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_eight_quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_eight_total_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_eight_unit_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_five',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_five_quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_five_total_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_five_unit_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_nine',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_nine_quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_nine_total_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_nine_unit_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_seven',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_seven_quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_seven_total_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_seven_unit_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_six',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_six_quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_six_total_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_six_unit_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_ten',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_ten_quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_ten_total_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_ten_unit_price',
        ),
    ]
