# Generated by Django 4.2.2 on 2023-06-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0003_remove_invoice_line_eight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('Invoice', 'Invoice'), ('Receipt', 'Receipt'), ('Proforma Invoice', 'Proforma Invoice')], max_length=50, null=True),
        ),
    ]
