# Generated by Django 4.2.1 on 2023-07-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0005_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='balance',
            field=models.CharField(blank=True, default='0', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four_quantity',
            field=models.CharField(blank=True, default=0, max_length=120, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four_total_price',
            field=models.CharField(blank=True, default=0, max_length=120, null=True, verbose_name='Line Total (D)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four_unit_price',
            field=models.CharField(blank=True, default=0, max_length=120, null=True, verbose_name='Unit Price (D)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one_quantity',
            field=models.CharField(blank=True, default=0, max_length=120, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one_total_price',
            field=models.CharField(blank=True, default=0, max_length=120, null=True, verbose_name='Line Total (D)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one_unit_price',
            field=models.CharField(blank=True, default=0, max_length=120, null=True, verbose_name='Unit Price (D)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three_quantity',
            field=models.CharField(blank=True, default=0, max_length=120, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three_total_price',
            field=models.CharField(blank=True, default=0, max_length=120, null=True, verbose_name='Line Total (D)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three_unit_price',
            field=models.CharField(blank=True, default=0, max_length=120, null=True, verbose_name='Unit Price (D)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two_quantity',
            field=models.CharField(blank=True, default=0, max_length=120, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two_total_price',
            field=models.CharField(blank=True, default=0, max_length=120, null=True, verbose_name='Line Total (D)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two_unit_price',
            field=models.CharField(blank=True, default=0, max_length=120, null=True, verbose_name='Unit Price (D)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.CharField(blank=True, default='0', max_length=120, null=True),
        ),
    ]
