# Generated by Django 4.2.1 on 2023-05-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_computer_operating_system_alter_computer_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operating_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_system', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='computer',
            name='operating_system',
        ),
        migrations.AddField(
            model_name='computer',
            name='operating_system',
            field=models.ManyToManyField(blank=True, to='djangoapp.operating_system'),
        ),
    ]
