# Generated by Django 4.2.1 on 2023-05-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_operating_system_remove_computer_operating_system_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email_address', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=8)),
                ('confirm_password', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='export_csv',
            field=models.BooleanField(default=False),
        ),
    ]
