# Generated by Django 4.2.1 on 2023-05-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_register_computer_export_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=30)),
                ('email_address', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.RenameField(
            model_name='register',
            old_name='middle_name',
            new_name='user_name',
        ),
    ]
