# Generated by Django 4.2.1 on 2023-05-29 06:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_login_rename_middle_name_register_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 29, 6, 29, 57, 221810, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
