# Generated by Django 4.2.1 on 2023-05-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_computer_purchase_date_computer_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
