# Generated by Django 4.2.1 on 2023-05-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_alter_computer_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='operating_system',
        ),
        migrations.AlterField(
            model_name='computer',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='purchase_date(mm/dd/yyyy)'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
