# Generated by Django 4.2.1 on 2023-05-31 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_computerhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='computerhistory',
            name='computer_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.update'),
        ),
    ]
