# Generated by Django 4.2.1 on 2023-05-30 11:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('issued_quantity', models.PositiveIntegerField(null=True)),
                ('issued_to', models.CharField(max_length=100)),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('received_quantity', models.PositiveIntegerField(null=True)),
                ('received_by', models.CharField(max_length=100)),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('reorder_level', models.PositiveIntegerField(null=True, unique=True)),
                ('name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.category')),
            ],
        ),
    ]
